#!/bin/bash
# 无雷达测试：用假传感器 + 预存地图 跑 Nav2 + 决策
# 需要：已有地图文件 (如 ~/nav_ws 或 ~/Desktop/map 下的 map.yaml + map.pgm)

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SENTRY_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# 地图路径（请根据实际修改）
# 默认使用项目自带的 RMUL 场地地图（高校联盟赛）
MAP_YAML="${MAP_YAML:-$SENTRY_ROOT/rm_navigation_ws/src/rm_nav_bringup/map/RMUL.yaml}"
NAV_PARAMS="${NAV_PARAMS:-/home/nyu/nav_ws/my_nav2_params.yaml}"

echo "=========================================="
echo "  无雷达测试 - Nav2 + 决策"
echo "  地图: $MAP_YAML"
echo "=========================================="
echo ""
echo "⚠️  若遇到 Permission denied 写 ~/.ros/log，请先执行："
echo "    sudo chown -R \$(whoami):\$(whoami) ~/.ros"
echo ""
echo "⚠️  若遇到 setup.sh not found，请新开终端或先执行："
echo "    unset AMENT_PREFIX_PATH COLCON_PREFIX_PATH"
echo ""
echo "请开 4 个终端，按顺序执行："
echo ""
echo "【终端 1】假传感器:"
echo "  unset AMENT_PREFIX_PATH COLCON_PREFIX_PATH  # 可选，避免 workspace 污染"
echo "  source /opt/ros/humble/setup.bash"
echo "  python3 $SCRIPT_DIR/fake_sensors_for_test.py"
echo ""
echo "【终端 2】地图服务器 + Nav2:"
echo "  source /opt/ros/humble/setup.bash"
echo "  source ~/nav_ws/install/setup.bash"
echo "  ros2 launch nav2_bringup bringup_launch.py \\"
echo "    use_sim_time:=False \\"
echo "    map:=$MAP_YAML \\"
echo "    params_file:=$NAV_PARAMS"
echo ""
echo "【终端 3】决策:"
echo "  source /opt/ros/humble/setup.bash"
echo "  source $SENTRY_ROOT/rm_vision_ws/install/setup.bash"
echo "  source $SENTRY_ROOT/rm_decision_ws/install/setup.bash"
echo "  ros2 launch rm_behavior_tree rm_behavior_tree.launch.py \\"
echo "    style:=retreat_attack_left use_sim_time:=False"
echo ""
echo "【终端 4】模拟裁判数据:"
echo "  source $SENTRY_ROOT/rm_decision_ws/install/setup.bash"
echo "  source $SENTRY_ROOT/rm_vision_ws/install/setup.bash"
echo "  ros2 topic pub -r 1 /game_status rm_decision_interfaces/msg/GameStatus \\"
echo "    '{game_progress: 4, stage_remain_time: 180}'"
echo ""
echo "或运行: $SENTRY_ROOT/rm_decision_ws/rm_decision_interfaces/publish_script.sh"
echo ""
